# Generated by Django 2.2 on 2020-12-01 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_favourites'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favourites',
            old_name='favorite',
            new_name='recipe',
        ),
    ]
