# Generated by Django 2.2 on 2020-12-04 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_purchases'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='unit',
            new_name='dimension',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='title_ing',
            new_name='title',
        ),
    ]
