# Generated by Django 2.2 on 2020-12-08 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20201204_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='quantity',
            field=models.ManyToManyField(blank=True, null=True, to='app.Quantity'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='tag',
            field=models.ManyToManyField(blank=True, null=True, to='app.Tag'),
        ),
    ]
