# Generated by Django 2.2 on 2020-12-12 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20201208_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='quantity',
            field=models.ManyToManyField(blank=True, to='app.Quantity'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='tag',
            field=models.ManyToManyField(blank=True, to='app.Tag'),
        ),
    ]
