from django.urls import path
from .views import (
    Index,
    single,
    author_ricipe,
    favourites,
    favourites_add,
    favourites_del,
    subscriptions_list,
    subscriptions_add,
    subscriptions_del,
    subscriptions_del_name,
    purchases,
    purchases_file,
    purchases_add,
    purchases_del,
    purchases_del_not_js,
    get_ingredients,
    create_recipe,
    recipe_edit,
    delete_recipe,
    base,
    create_tags,
)

urlpatterns = [
    path('', Index.as_view(), name='index'),
    path('base', base),
    path('create_tags/', create_tags),
    path('create/', create_recipe, name='create'),
    path('<str:username>/<int:id>/edit/', recipe_edit, name='recipe_edit'),
    path('<str:username>/<int:id>/del/', delete_recipe, name='del_recipe'),
    path('ingredients', get_ingredients),
    path('purchases/del/<int:id>', purchases_del_not_js, name='purchases_del_not_js'),
    path('purchases', purchases_add),
    path('purchases/<int:id>', purchases_del),
    path('purchases_shop/', purchases, name='purchases'),
    path('purchases_file/', purchases_file, name='purchases_file'),
    path('follow/', subscriptions_list, name='follow'),
    path('subscriptions', subscriptions_add),
    path('subscriptions/<int:id>', subscriptions_del),
    path('subscript/<str:username>', subscriptions_del_name),
    path('favourites/', favourites, name='favourites'),
    path('favorites/<int:id>', favourites_del),
    path('favorites', favourites_add),
    path('<str:username>/', author_ricipe, name='author_recipe'),
    path('index/<int:recipe_id>/', single, name='single'),
]
